spring:
    datasource:
        username: regdemouser_rw
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/regdemo

upload_dictionary: /Users/jinsong/IdeaProjects/regdemo/src/main/resources/uploadFiles/

spring.thymeleaf.prefix: classpath:/templates/
spring.thymeleaf.suffix: .html
spring.thymeleaf.mode: HTML5
spring.thymeleaf.encoding: UTF-8
spring.thymeleaf.content-type: text/html
spring.thymeleaf.cache: false

