spring:
    datasource:
        username: regdemouser_rw
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/regdemo?serverTimezone=UTC

#Windows文件路径分隔符使用'/'
#eg：D:/IdeaProjects/regdemo/src/main/resources/uploadFiles/
#Linux文件路径正常使用
#eg:/home/LJQ/deaProjects/regdemo/src/main/resources/uploadFiles/
upload_dictionary: D:/IdeaProjects/regdemo/src/main/resources/uploadFiles/

spring.thymeleaf.prefix: classpath:/templates/
spring.thymeleaf.suffix: .html
spring.thymeleaf.mode: HTML5
spring.thymeleaf.encoding: UTF-8
spring.thymeleaf.content-type: text/html
spring.thymeleaf.cache: false

